//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecuResume.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOGS
    {
        public int ID { get; set; }
        public string PARSED_FILE_NAME { get; set; }
        public Nullable<System.DateTime> PROCESS_DATETIME { get; set; }
        public string REQUEST_IP { get; set; }
        public string ORIGIN_ADDRESS { get; set; }
        public string CRE_USER { get; set; }
        public Nullable<System.DateTime> CRE_DATE { get; set; }
        public string UPD_USER { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string DEL_USER { get; set; }
        public Nullable<System.DateTime> DEL_DATE { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
