//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecuResume.RChilliParserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://RchilliResumeParser", ConfigurationName="RChilliParserService.RChilliParserPortType")]
    public interface RChilliParserPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResumeBinaryWithCategory", ReplyAction="urn:parseResumeBinaryWithCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryResponse parseResumeBinaryWithCategory(ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResumeBinaryWithCategory", ReplyAction="urn:parseResumeBinaryWithCategoryResponse")]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryResponse> parseResumeBinaryWithCategoryAsync(ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ParseResumeWithCountry", ReplyAction="urn:ParseResumeWithCountryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ExecuResume.RChilliParserService.ParseResumeWithCountryResponse ParseResumeWithCountry(ExecuResume.RChilliParserService.ParseResumeWithCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ParseResumeWithCountry", ReplyAction="urn:ParseResumeWithCountryResponse")]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.ParseResumeWithCountryResponse> ParseResumeWithCountryAsync(ExecuResume.RChilliParserService.ParseResumeWithCountryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResumeBinary", ReplyAction="urn:parseResumeBinaryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ExecuResume.RChilliParserService.parseResumeBinaryResponse parseResumeBinary(ExecuResume.RChilliParserService.parseResumeBinaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResumeBinary", ReplyAction="urn:parseResumeBinaryResponse")]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryResponse> parseResumeBinaryAsync(ExecuResume.RChilliParserService.parseResumeBinaryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResume", ReplyAction="urn:parseResumeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ExecuResume.RChilliParserService.parseResumeResponse parseResume(ExecuResume.RChilliParserService.parseResumeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResume", ReplyAction="urn:parseResumeResponse")]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeResponse> parseResumeAsync(ExecuResume.RChilliParserService.parseResumeRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResumeBinaryWithCountry", ReplyAction="urn:parseResumeBinaryWithCountryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ExecuResume.RChilliParserService.parseResumeBinaryWithCountryResponse parseResumeBinaryWithCountry(ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:parseResumeBinaryWithCountry", ReplyAction="urn:parseResumeBinaryWithCountryResponse")]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryWithCountryResponse> parseResumeBinaryWithCountryAsync(ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:buildRelease", ReplyAction="urn:buildReleaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ExecuResume.RChilliParserService.buildReleaseResponse buildRelease(ExecuResume.RChilliParserService.buildReleaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:buildRelease", ReplyAction="urn:buildReleaseResponse")]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.buildReleaseResponse> buildReleaseAsync(ExecuResume.RChilliParserService.buildReleaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResumeBinaryWithCategory", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeBinaryWithCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filedata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CategoryXml;
        
        public parseResumeBinaryWithCategoryRequest() {
        }
        
        public parseResumeBinaryWithCategoryRequest(string filedata, string fileName, string userkey, string version, string subUserId, string CategoryXml) {
            this.filedata = filedata;
            this.fileName = fileName;
            this.userkey = userkey;
            this.version = version;
            this.subUserId = subUserId;
            this.CategoryXml = CategoryXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResumeBinaryWithCategoryResponse", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeBinaryWithCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public parseResumeBinaryWithCategoryResponse() {
        }
        
        public parseResumeBinaryWithCategoryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParseResumeWithCountry", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class ParseResumeWithCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subUserId;
        
        public ParseResumeWithCountryRequest() {
        }
        
        public ParseResumeWithCountryRequest(string url, string userkey, string version, string CountryKey, string subUserId) {
            this.url = url;
            this.userkey = userkey;
            this.version = version;
            this.CountryKey = CountryKey;
            this.subUserId = subUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParseResumeWithCountryResponse", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class ParseResumeWithCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ParseResumeWithCountryResponse() {
        }
        
        public ParseResumeWithCountryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResumeBinary", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeBinaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filedata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subUserId;
        
        public parseResumeBinaryRequest() {
        }
        
        public parseResumeBinaryRequest(string filedata, string fileName, string userkey, string version, string subUserId) {
            this.filedata = filedata;
            this.fileName = fileName;
            this.userkey = userkey;
            this.version = version;
            this.subUserId = subUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResumeBinaryResponse", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeBinaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public parseResumeBinaryResponse() {
        }
        
        public parseResumeBinaryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResume", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subUserId;
        
        public parseResumeRequest() {
        }
        
        public parseResumeRequest(string url, string userkey, string version, string subUserId) {
            this.url = url;
            this.userkey = userkey;
            this.version = version;
            this.subUserId = subUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResumeResponse", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public parseResumeResponse() {
        }
        
        public parseResumeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResumeBinaryWithCountry", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeBinaryWithCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filedata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subUserId;
        
        public parseResumeBinaryWithCountryRequest() {
        }
        
        public parseResumeBinaryWithCountryRequest(string filedata, string fileName, string userkey, string version, string CountryKey, string subUserId) {
            this.filedata = filedata;
            this.fileName = fileName;
            this.userkey = userkey;
            this.version = version;
            this.CountryKey = CountryKey;
            this.subUserId = subUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="parseResumeBinaryWithCountryResponse", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class parseResumeBinaryWithCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public parseResumeBinaryWithCountryResponse() {
        }
        
        public parseResumeBinaryWithCountryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buildRelease", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class buildReleaseRequest {
        
        public buildReleaseRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buildReleaseResponse", WrapperNamespace="http://RchilliResumeParser", IsWrapped=true)]
    public partial class buildReleaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RchilliResumeParser", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public buildReleaseResponse() {
        }
        
        public buildReleaseResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RChilliParserPortTypeChannel : ExecuResume.RChilliParserService.RChilliParserPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RChilliParserPortTypeClient : System.ServiceModel.ClientBase<ExecuResume.RChilliParserService.RChilliParserPortType>, ExecuResume.RChilliParserService.RChilliParserPortType {
        
        public RChilliParserPortTypeClient() {
        }
        
        public RChilliParserPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RChilliParserPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RChilliParserPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RChilliParserPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryResponse ExecuResume.RChilliParserService.RChilliParserPortType.parseResumeBinaryWithCategory(ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest request) {
            return base.Channel.parseResumeBinaryWithCategory(request);
        }
        
        public string parseResumeBinaryWithCategory(string filedata, string fileName, string userkey, string version, string subUserId, string CategoryXml) {
            ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest inValue = new ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest();
            inValue.filedata = filedata;
            inValue.fileName = fileName;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.subUserId = subUserId;
            inValue.CategoryXml = CategoryXml;
            ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryResponse retVal = ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResumeBinaryWithCategory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryResponse> ExecuResume.RChilliParserService.RChilliParserPortType.parseResumeBinaryWithCategoryAsync(ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest request) {
            return base.Channel.parseResumeBinaryWithCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryResponse> parseResumeBinaryWithCategoryAsync(string filedata, string fileName, string userkey, string version, string subUserId, string CategoryXml) {
            ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest inValue = new ExecuResume.RChilliParserService.parseResumeBinaryWithCategoryRequest();
            inValue.filedata = filedata;
            inValue.fileName = fileName;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.subUserId = subUserId;
            inValue.CategoryXml = CategoryXml;
            return ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResumeBinaryWithCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExecuResume.RChilliParserService.ParseResumeWithCountryResponse ExecuResume.RChilliParserService.RChilliParserPortType.ParseResumeWithCountry(ExecuResume.RChilliParserService.ParseResumeWithCountryRequest request) {
            return base.Channel.ParseResumeWithCountry(request);
        }
        
        public string ParseResumeWithCountry(string url, string userkey, string version, string CountryKey, string subUserId) {
            ExecuResume.RChilliParserService.ParseResumeWithCountryRequest inValue = new ExecuResume.RChilliParserService.ParseResumeWithCountryRequest();
            inValue.url = url;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.CountryKey = CountryKey;
            inValue.subUserId = subUserId;
            ExecuResume.RChilliParserService.ParseResumeWithCountryResponse retVal = ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).ParseResumeWithCountry(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.ParseResumeWithCountryResponse> ExecuResume.RChilliParserService.RChilliParserPortType.ParseResumeWithCountryAsync(ExecuResume.RChilliParserService.ParseResumeWithCountryRequest request) {
            return base.Channel.ParseResumeWithCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExecuResume.RChilliParserService.ParseResumeWithCountryResponse> ParseResumeWithCountryAsync(string url, string userkey, string version, string CountryKey, string subUserId) {
            ExecuResume.RChilliParserService.ParseResumeWithCountryRequest inValue = new ExecuResume.RChilliParserService.ParseResumeWithCountryRequest();
            inValue.url = url;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.CountryKey = CountryKey;
            inValue.subUserId = subUserId;
            return ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).ParseResumeWithCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExecuResume.RChilliParserService.parseResumeBinaryResponse ExecuResume.RChilliParserService.RChilliParserPortType.parseResumeBinary(ExecuResume.RChilliParserService.parseResumeBinaryRequest request) {
            return base.Channel.parseResumeBinary(request);
        }
        
        public string parseResumeBinary(string filedata, string fileName, string userkey, string version, string subUserId) {
            ExecuResume.RChilliParserService.parseResumeBinaryRequest inValue = new ExecuResume.RChilliParserService.parseResumeBinaryRequest();
            inValue.filedata = filedata;
            inValue.fileName = fileName;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.subUserId = subUserId;
            ExecuResume.RChilliParserService.parseResumeBinaryResponse retVal = ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResumeBinary(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryResponse> ExecuResume.RChilliParserService.RChilliParserPortType.parseResumeBinaryAsync(ExecuResume.RChilliParserService.parseResumeBinaryRequest request) {
            return base.Channel.parseResumeBinaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryResponse> parseResumeBinaryAsync(string filedata, string fileName, string userkey, string version, string subUserId) {
            ExecuResume.RChilliParserService.parseResumeBinaryRequest inValue = new ExecuResume.RChilliParserService.parseResumeBinaryRequest();
            inValue.filedata = filedata;
            inValue.fileName = fileName;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.subUserId = subUserId;
            return ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResumeBinaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExecuResume.RChilliParserService.parseResumeResponse ExecuResume.RChilliParserService.RChilliParserPortType.parseResume(ExecuResume.RChilliParserService.parseResumeRequest request) {
            return base.Channel.parseResume(request);
        }
        
        public string parseResume(string url, string userkey, string version, string subUserId) {
            ExecuResume.RChilliParserService.parseResumeRequest inValue = new ExecuResume.RChilliParserService.parseResumeRequest();
            inValue.url = url;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.subUserId = subUserId;
            ExecuResume.RChilliParserService.parseResumeResponse retVal = ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResume(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeResponse> ExecuResume.RChilliParserService.RChilliParserPortType.parseResumeAsync(ExecuResume.RChilliParserService.parseResumeRequest request) {
            return base.Channel.parseResumeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeResponse> parseResumeAsync(string url, string userkey, string version, string subUserId) {
            ExecuResume.RChilliParserService.parseResumeRequest inValue = new ExecuResume.RChilliParserService.parseResumeRequest();
            inValue.url = url;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.subUserId = subUserId;
            return ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResumeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExecuResume.RChilliParserService.parseResumeBinaryWithCountryResponse ExecuResume.RChilliParserService.RChilliParserPortType.parseResumeBinaryWithCountry(ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest request) {
            return base.Channel.parseResumeBinaryWithCountry(request);
        }
        
        public string parseResumeBinaryWithCountry(string filedata, string fileName, string userkey, string version, string CountryKey, string subUserId) {
            ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest inValue = new ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest();
            inValue.filedata = filedata;
            inValue.fileName = fileName;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.CountryKey = CountryKey;
            inValue.subUserId = subUserId;
            ExecuResume.RChilliParserService.parseResumeBinaryWithCountryResponse retVal = ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResumeBinaryWithCountry(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryWithCountryResponse> ExecuResume.RChilliParserService.RChilliParserPortType.parseResumeBinaryWithCountryAsync(ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest request) {
            return base.Channel.parseResumeBinaryWithCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExecuResume.RChilliParserService.parseResumeBinaryWithCountryResponse> parseResumeBinaryWithCountryAsync(string filedata, string fileName, string userkey, string version, string CountryKey, string subUserId) {
            ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest inValue = new ExecuResume.RChilliParserService.parseResumeBinaryWithCountryRequest();
            inValue.filedata = filedata;
            inValue.fileName = fileName;
            inValue.userkey = userkey;
            inValue.version = version;
            inValue.CountryKey = CountryKey;
            inValue.subUserId = subUserId;
            return ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).parseResumeBinaryWithCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExecuResume.RChilliParserService.buildReleaseResponse ExecuResume.RChilliParserService.RChilliParserPortType.buildRelease(ExecuResume.RChilliParserService.buildReleaseRequest request) {
            return base.Channel.buildRelease(request);
        }
        
        public string buildRelease() {
            ExecuResume.RChilliParserService.buildReleaseRequest inValue = new ExecuResume.RChilliParserService.buildReleaseRequest();
            ExecuResume.RChilliParserService.buildReleaseResponse retVal = ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).buildRelease(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExecuResume.RChilliParserService.buildReleaseResponse> ExecuResume.RChilliParserService.RChilliParserPortType.buildReleaseAsync(ExecuResume.RChilliParserService.buildReleaseRequest request) {
            return base.Channel.buildReleaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExecuResume.RChilliParserService.buildReleaseResponse> buildReleaseAsync() {
            ExecuResume.RChilliParserService.buildReleaseRequest inValue = new ExecuResume.RChilliParserService.buildReleaseRequest();
            return ((ExecuResume.RChilliParserService.RChilliParserPortType)(this)).buildReleaseAsync(inValue);
        }
    }
}
